#' Simulated time series with AR(1) errors for the autocorrelation chapter
#'
#' A simulated dataset of length 120 used in Chapter 8 (Autocorrelation)
#' of the textbook. Sales are generated from a deterministic trend in
#' advertising plus an AR(1) error process with autocorrelation
#' coefficient rho = 0.7, providing a controlled setting to illustrate
#' the Durbin-Watson and Breusch-Godfrey tests and the consequences of
#' ignoring serial correlation.
#'
#' @format A data frame with 120 rows and 3 variables:
#' \describe{
#'   \item{time}{integer time index (1-120).}
#'   \item{advertising}{simulated advertising expenditure (trending series
#'     with Gaussian noise).}
#'   \item{sales}{simulated sales, equal to
#'     \eqn{10 + 0.8 \cdot advertising + 0.3 \cdot time + u_t}, where
#'     \eqn{u_t = 0.7 \, u_{t-1} + \varepsilon_t}.}
#' }
#' @source Generated by the script \code{data-raw/autocorr_demo.R}
#'   (set.seed(2026)). Used as a running example in Chapter 8 of the
#'   UGR Econometria I textbook.
"autocorr_demo"
